In [1]:
import pandas as pd

df = pd.read_csv('synthetic_customer_dataset_5000.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,56,Female,Skirt,Footwear,15,New York,XL,Blue,Spring,4,Yes,Free Shipping,Yes,No,29,PayPal,Weekly
1,2,69,Male,Skirt,Footwear,21,Phoenix,XXL,Green,Fall,2,No,Next Day Air,Yes,Yes,24,Bank Transfer,Weekly
2,3,46,Female,Jacket,Accessories,14,Los Angeles,L,Brown,Summer,3,No,Standard,Yes,Yes,39,Credit Card,Monthly
3,4,32,Male,Jeans,Clothing,64,Chicago,M,Brown,Spring,2,Yes,Free Shipping,No,No,34,Bank Transfer,Weekly
4,5,60,Male,Blouse,Clothing,127,Los Angeles,XL,White,Fall,3,No,Next Day Air,Yes,No,36,Cash,Quarterly

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5000 non-null   int64
 1   Age                     5000 non-null   int64
 2   Gender                  5000 non-null   object
 3   Item Purchased          5000 non-null   object
 4   Category                5000 non-null   object
 5   Purchase Amount (USD)   5000 non-null   int64
 6   Location                5000 non-null   object
 7   Size                    5000 non-null   object
 8   Color                   5000 non-null   object
 9   Season                  5000 non-null   object
 10  Review Rating           5000 non-null   int64
 11  Subscription Status     5000 non-null   object
 12  Shipping Type           5000 non-null   object
 13  Discount Applied        5000 non-null   object
 14  Promo Code Used         5000 non-null   object
 15  Previous Purchases      5000 non-null   int64
 16  Payment Method          5000 non-null   object
 17  Frequency of Purchases  5000 non-null   object
dtypes: int64(5), object(13)
memory usage: 703.2+ KB

In [3]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,5000.000000,5000.000000,5000,5000,5000,5000.000000,5000,5000,5000,5000,5000.000000,5000,5000,5000,5000,5000.000000,5000,5000
unique,NaN,NaN,2,14,3,NaN,10,5,10,4,NaN,2,4,2,2,NaN,5,5
top,NaN,NaN,Female,Coat,Footwear,NaN,Houston,XXL,Pink,Summer,NaN,No,Next Day Air,Yes,No,NaN,Cash,Quarterly
freq,NaN,NaN,2517,402,1683,NaN,537,1098,528,1280,NaN,2546,1281,2517,2512,NaN,1036,1027
mean,2500.500000,44.131200,NaN,NaN,NaN,254.473800,NaN,NaN,NaN,NaN,2.995800,NaN,NaN,NaN,NaN,24.871000,NaN,NaN
std,1443.520003,15.213135,NaN,NaN,NaN,142.741935,NaN,NaN,NaN,NaN,1.202693,NaN,NaN,NaN,NaN,14.662352,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1250.750000,31.000000,NaN,NaN,NaN,129.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,12.000000,NaN,NaN
50%,2500.500000,44.000000,NaN,NaN,NaN,253.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3750.250000,57.000000,NaN,NaN,NaN,381.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,37.000000,NaN,NaN
max,5000.000000,70.000000,NaN,NaN,NaN,500.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [4]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [5]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [6]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [7]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [8]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [9]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age','age_group']].head(10)

   age    age_group
0   56  Middle-aged
1   69       Senior
2   46  Middle-aged
3   32        Adult
4   60       Senior
5   25  Young Adult
6   38        Adult
7   56  Middle-aged
8   36        Adult
9   40        Adult

In [10]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                        7                 Weekly
1                        7                 Weekly
2                       30                Monthly
3                        7                 Weekly
4                       90              Quarterly
5                        7                 Weekly
6                        7                 Weekly
7                       30                Monthly
8                      365               Annually
9                       90              Quarterly

In [11]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes              No
1              Yes             Yes
2              Yes             Yes
3               No              No
4              Yes              No
5              Yes              No
6              Yes              No
7              Yes              No
8               No             Yes
9               No             Yes

In [12]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [14]:
df = df.drop('promo_code_used', axis=1)

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [13]:
%pip install sqlalchemy psycopg2-binary pandas

Requirement already satisfied: sqlalchemy in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (2.1.4)
Requirement already satisfied: psycopg2-binary in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (2.9.13)
Requirement already satisfied: pandas in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.23.2 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\dhars\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# PostgreSQL connection details
username = "postgres"
password = "dharsh@1516"
host = "localhost"
port = 5432
database = "customer_shopping"

connection_url = URL.create(
    "postgresql+psycopg2",
    username=username,
    password=password,
    host=host,
    port=port,
    database=database
)

engine = create_engine(connection_url)

# Upload your existing DataFrame
table_name = "customer"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Successfully loaded {len(df)} rows into '{table_name}'!")

engine.dispose()

Successfully loaded 5000 rows into 'customer'!